ext4: Remove unused inode variable
Subsequent to 62a3a66 ("ext4: don't bother checking for encryption key in ->mmap()"),
inode is no longer used in ext4_file_mmap. Remove it to silence the following
compiler warning:

../fs/ext4/file.c:297:16: error: unused variable 'inode' [-Werror,-Wunused-variable]
        struct inode *inode = file->f_mapping->host;
                      ^

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>